### PR TITLE
Test with PHP 8.0

### PR DESCRIPTION
**Pull request by phil-davis**

### CODE REVIEW

**Comment by phil-davis** [comment]
https://travis-ci.org/github/sabre-io/resourcelocator/jobs/732500092 unit tests on PHP 8.0
`OK (8 tests, 13 assertions)`
good

**Comment by phil-davis** [comment]
@staabm this has not had an official release created since 2015. I guess that we don't bother making official releases?

**Comment by staabm** [comment]
Agree.

**Comment by evert** [comment]
If there's more than 0 users of this id be surprised. Feel free to archive this repo

**Pull request merged**
